# Generated by Django 2.0.5 on 2018-05-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='last_mmodified',
            new_name='last_modified',
        ),
    ]
